# Front-end image for Facenet
FROM tensorflow/tensorflow

#install required Linux packages
RUN apt-get update && apt-get install -y \
  git \
  npm \
  sudo

#extra steps are needed to install NodeJs 6.x
RUN curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
RUN apt-get install -y nodejs

#git clone Web-UI repositories
RUN git clone https://github.com/yhj2263/Facenet-Web-UI.git ~/Facenet-Web-UI

#install express
RUN npm install -g vue-cli

#install NodeJS dependencies
RUN cd ~/Facenet-Web-UI && npm install
EXPOSE 8080
#run the UI
CMD cd ~/Facenet-Web-UI && npm start dev
